---
# user role 默认变量
system_users:
  - name: "www"
    group: "www"
    uid: 701
    shell: "/bin/bash"
    sudo: true
  - name: "rouser"
    group: "rouser"
    uid: 1000
    shell: "/bin/bash"
    sudo: false