---
- name: 服务器初始化
  hosts: "{{ webserver }}"
  become: yes
  gather_facts: yes

  roles:
    - role: common
    - role: user
    - role: disk
    - role: directory
    - role: sysctl
    - role: system_update
